apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: movies
  name: movies
spec:
  ports:
  - name: "3010"
    port: 3010
    protocol: TCP
    targetPort: 3010
  selector:
    app: movies
  type: NodePort
status:
  loadBalancer: {}
