apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movies
spec:
  rules:
    - http:
        paths:
          - path: /movies/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: movies
                port:
                  number: 3010
