apiVersion: v1
kind: Service
metadata:
  labels:
    app: movies
  name: movies
spec:
  ports:
  - name: "http"
    port: 3010
    protocol: TCP
    targetPort: 3010
  selector:
    app: movies
  type: NodePort
